import type { AssessmentResult } from '../domain/types.js';

// Deterministic report renderer (BRD 25.3). Produces a recruiter-ready plain
// text / markdown report from a structured assessment. Never invents narrative.

export function renderReportMarkdown(opts: {
  candidateName: string;
  roleTitle: string;
  assessment: AssessmentResult;
}): string {
  const a = opts.assessment;
  const recLabel = a.recommendation.replace(/_/g, ' ');
  const lines: string[] = [];
  lines.push(`# Interview Assessment — ${opts.candidateName}`);
  lines.push(`**Role:** ${opts.roleTitle}`);
  lines.push(`**Recommendation:** ${recLabel}  |  **Confidence:** ${pct(a.confidence)}  |  **Evidence coverage:** ${pct(a.evidenceCoverage)}  |  **Overall:** ${a.overallScore}/100`);
  lines.push('');
  // Welded to the recommendation line, not filed under Limitations at the
  // bottom. This artifact is what gets pasted into an ATS or forwarded to a
  // hiring manager — the number travels and the on-screen warning does not, so
  // the person most likely to act on the score was the person least likely to
  // ever see the caveat. Anyone reading only the first three lines still reads
  // this one.
  lines.push('> **This recommendation comes from an instrument that has not been validated against human judgement.**');
  lines.push('> Agreement between these scores and blind human review has not been established. Treat this as one');
  lines.push('> opinion to argue with, not a measurement. A person must read the transcript and decide.');
  lines.push('');
  lines.push('## Executive summary');
  lines.push(a.summary);
  lines.push('');
  lines.push('## Competency scorecard');
  lines.push('| Competency | Level | Required | Confidence | Evidence |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const c of a.competencies) {
    const level = c.notEnoughEvidence ? 'Not Enough Evidence' : `${c.level}/5`;
    lines.push(`| ${c.name} | ${level} | ${c.requiredLevel}/5 | ${pct(c.confidence)} | ${c.evidence.length} span(s) |`);
  }
  lines.push('');
  if (a.strengths.length) { lines.push('## Strengths'); a.strengths.forEach((s) => lines.push(`- ${s}`)); lines.push(''); }
  if (a.concerns.length) { lines.push('## Concerns'); a.concerns.forEach((s) => lines.push(`- ${s}`)); lines.push(''); }
  if (a.contradictions.length) { lines.push('## Contradictions / items for review'); a.contradictions.forEach((s) => lines.push(`- ${s}`)); lines.push(''); }
  if (a.openQuestions.length) { lines.push('## Open questions'); a.openQuestions.forEach((s) => lines.push(`- ${s}`)); lines.push(''); }
  if (a.limitations.length) { lines.push('## Limitations'); a.limitations.forEach((s) => lines.push(`- ${s}`)); lines.push(''); }
  lines.push('## Rationale by competency');
  for (const c of a.competencies) {
    lines.push(`### ${c.name}`);
    lines.push(c.rationale);
    if (c.evidence.length) {
      lines.push('Evidence:');
      c.evidence.slice(0, 3).forEach((e) => lines.push(`> "${e.quote}" _(turn ${e.turnId}, ${fmtMs(e.startMs)})_`));
    }
    lines.push('');
  }
  lines.push('---');
  lines.push('_Generated by Questor. This is decision-support for a first-round screen; a human makes the final decision (BRD principle: Human accountability)._');
  return lines.join('\n');
}

function pct(v: number): string { return `${Math.round(v * 100)}%`; }
function fmtMs(ms: number): string {
  const s = Math.floor(ms / 1000);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
}
