import { useState } from 'react';
import { api, ApiError } from '../api/client';
import { useAuth } from '../auth';
import { Banner } from '../components/ui';
import { PageHeader } from '../components/PageHeader';
import { PageSkeleton } from '../components/Skeleton';
import { WorkerStatusPanel } from '../components/library/WorkerStatusPanel';
import { PoolHealthTable } from '../components/library/PoolHealthTable';
import { EntryReviewList, type ReviewAction } from '../components/library/EntryReviewList';
import { EntryDetail } from '../components/library/EntryDetail';
import { TrialReportPanel } from '../components/library/TrialReportPanel';
import { useLibraryAdminData } from '../components/library/useLibraryAdminData';
import { decisionMessage, percent, stratumLabel, type EntryView } from '../components/library/libraryAdminModel';
import { useToast } from '../components/Toast';

type Notice = { readonly kind: 'ok' | 'info' | 'error'; readonly text: string };

/**
 * The platform owner's view of the question library: is the worker filling,
 * what does it cost, which pools are thin, what waits for a decision, and
 * today's sample of what the gate let through.
 */
export function LibraryAdmin() {
  const { user } = useAuth();
  const isOperator = user?.platformOperator === true;
  const data = useLibraryAdminData(isOperator);
  const [busyIds, setBusyIds] = useState<ReadonlySet<string>>(new Set());
  const [openId, setOpenId] = useState<string | null>(null);
  const [notice, setNotice] = useState<Notice | null>(null);
  const toast = useToast();

  if (!isOperator) {
    return (
      <div>
        <PageHeader icon="list" title="Question library" />
        <Banner kind="info">Only the platform owner can work the question library.</Banner>
      </div>
    );
  }
  if (data.loading && !data.overview && !data.loadError) return <PageSkeleton label="Loading the question library…" />;

  const markBusy = (id: string, busy: boolean) => setBusyIds((current) => (busy ? new Set([...current, id]) : new Set([...current].filter((v) => v !== id))));

  const decide = async (entry: EntryView, action: ReviewAction, payload: { readonly reason?: string; readonly questionText?: string }) => {
    markBusy(entry.id, true);
    try {
      await api.post(`/library/admin/entries/${entry.id}/${action}`, action === 'reject' ? { reason: payload.reason ?? '' } : action === 'edit' ? { questionText: payload.questionText ?? '' } : {});
      toast.show(decisionMessage(action, true));
    } catch (err: unknown) {
      const apiErr = err instanceof ApiError ? err : null;
      setNotice({ kind: apiErr?.code === 'invalid_transition' ? 'info' : 'error', text: decisionMessage(action, false, apiErr?.code) });
    } finally {
      markBusy(entry.id, false);
      await Promise.all([data.loadQueue(), data.loadSample(), data.loadOverview(), data.loadPools()]);
    }
  };

  return (
    <div className="library-admin">
      <PageHeader
        icon="list"
        title="Question library"
        subtitle="Role-specific questions and shared scoring standards, generated by the worker and gated by the critic, the linter and you."
        actions={<button type="button" className="btn secondary" onClick={() => void data.loadAll()}>Refresh</button>}
      />
      <div aria-live="polite" aria-atomic="true">
        {notice && <Banner kind={notice.kind}>{notice.text}</Banner>}
      </div>
      {data.loadError && (
        <Banner kind="error">
          {data.loadError}{' '}
          <button type="button" className="btn ghost sm" onClick={() => { data.setLoadError(''); void data.loadAll(); }}>Try again</button>
        </Banner>
      )}

      {data.overview && <WorkerStatusPanel overview={data.overview} />}

      {openId && <EntryDetail entryId={openId} onClose={() => setOpenId(null)} />}

      <section className="card" aria-labelledby="library-queue-heading">
        <h2 id="library-queue-heading" className="library-section-title">Your queue <span className="muted small">({data.queueTotal})</span></h2>
        <p className="muted small">Entries the gate was unsure about, and every entry of a new pool or generator version until twenty of its stratum are approved untouched.</p>
        <EntryReviewList
          entries={data.queue} kind="queue" busyIds={busyIds} onDecide={decide} onOpen={(e) => setOpenId(e.id)}
          emptyTitle="Nothing waiting" emptyMessage="The gate has nothing it is unsure about. New pools will bring more."
        />
      </section>

      <section className="card" aria-labelledby="library-sample-heading">
        <h2 id="library-sample-heading" className="library-section-title">Today's sample <span className="muted small">({data.sample.length})</span></h2>
        <p className="muted small">Twenty entries the gate let through, drawn across pools, bands, forms and generator versions and weighted to what was filled since yesterday. A rejection here tightens that stratum's gate for its next 200 entries.</p>
        <EntryReviewList
          entries={data.sample} kind="sample" busyIds={busyIds} onDecide={decide} onOpen={(e) => setOpenId(e.id)}
          emptyTitle="No sample today" emptyMessage="Nothing probational or live is left to sample."
        />
      </section>

      <TrialReportPanel />

      <section className="card" aria-labelledby="library-pools-heading">
        <h2 id="library-pools-heading" className="library-section-title">Pool health</h2>
        <PoolHealthTable pools={data.pools} />
      </section>

      <section className="card" aria-labelledby="library-strata-heading">
        <h2 id="library-strata-heading" className="library-section-title">Rates by stratum</h2>
        {data.strata.length === 0 ? <p className="muted small">No entries yet.</p> : (
          <div className="table-scroll" tabIndex={0} role="region" aria-label="Rates by stratum">
            <table className="library-strata" data-testid="library-strata">
              <thead><tr><th>Stratum</th><th>Entries</th><th>Through the gate</th><th>Rejected</th><th>Owner approvals</th><th>Tightened</th></tr></thead>
              <tbody>
                {data.strata.map((s) => (
                  <tr key={s.stratumKey}>
                    <td>{stratumLabel(s.stratumKey)}</td>
                    <td>{s.total}</td>
                    <td>{percent(s.promotionRate)}</td>
                    <td>{percent(s.rejectionRate)}</td>
                    <td>{s.cleanApprovals}</td>
                    <td>{s.tightenedRemaining > 0 ? `${s.tightenedRemaining} to go` : '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}
